apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
  name: test-nginx
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30338
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 32689
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
